import type { Metadata } from "next";
import { Geist, Figtree } from "next/font/google";
import "./globals.css";
import Nav from "@/components/global/nav/Nav";

const figtree = Figtree({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={figtree.variable}>
      <body
        className={`${geistSans.variable} antialiased `}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
